name: Web in AKS

# Deploy the Tailwind Traders Web as a deployment in a EXISTING AKS THAT ALREADY HAS THE BACKEND INSTALLED
#
# Note: The AKS MUST HAVE TLS INSTALLED (Please refer to .....). Installing the web on AKS without TLS enabled is not supported.

# on:
#   push:
#     branches:
#       - master

on: [push]

jobs:
  buildpush:
    env:
      # TT public environment variables. Please edit to match your environment
      # akshost: backend.tailwindtraders.com            # AKS HOST NAME: You must use your AKS DNS name      
      akshost: fcacb0f417a84590bb54.eastus.aksapp.io            # AKS HOST NAME: You must use your AKS DNS name
      tlsSecretName: tt-tls-custom                    # AKS SECRET NAME HAVING THE TLS CERT
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1

    # - uses: azure/docker-login@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }} 
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    # - name: Docker build and push
    #   working-directory: Source/Tailwind.Traders.Web
    #   run: | 
    #     docker build . --build-arg sdkTag=2.1 --build-arg runtimeTag=2.1 -t tailwindtraders/web:gh-${{ github.sha }} -t latest
    #     docker push tailwindtraders/web:gh-${{ github.sha }}

    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Set AKS kubectl context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh
        export PATH=/usr/local/bin/helm

    - name: Install Helm Chart
      shell: pwsh

      run: |
        # helm upgrade --install tailwindtraders-web ./Deploy/helm/web -f ./Deploy/helm/gvalues.yaml -f ./Deploy/helm/values.b2c.yaml  --set ingress.hosts={$aksHost}  --set ingress.protocol=https --set ingress.tls[0].hosts={$aksHost}  --set ingress.tls[0].secretName=$tlsSecretName --set image.repository=tailwindtraders/web --set image.tag=gh-${{ github.sha }}
        helm upgrade --install tailwindtraders-web ./Deploy/helm/web -f ./Deploy/helm/gvalues.yaml -f ./Deploy/helm/values.b2c.yaml  --set ingress.hosts={$aksHost}  --set ingress.protocol=http --set image.repository=ivilches/tests --set image.tag=gh-b091f7dfc8019ce86c5a36b5185a214c02f3bacb
