# Web Workflow

name: Web in AKS

on: [push]

jobs:
  buildpush:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    # - name: Docker build and push
    #   working-directory: Source/Tailwind.Traders.Web
    #   run: | 
    #     # docker build . --build-arg sdkTag=2.1 --build-arg runtimeTag=2.1 -t tailwindtraders/web:gh-${{ github.sha }} -t latest
    #     # docker push tailwindtraders/web:gh-${{ github.sha }}
    #     docker build . --build-arg sdkTag=2.1 --build-arg runtimeTag=2.1 -t ivilches/tests:gh-${{ github.sha }} -t latest
    #     docker push ivilches/tests:gh-${{ github.sha }}

    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Set AKS kubectl context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}
    # - name: Fetch AKS host
    #   shell: pwsh
    #   run: $(az aks show -n ${{ secrets.CLUSTER_NAME }} -g ${{ secrets.RESOURCE_GROUP }} | ConvertFrom-Json).addonProfiles.httpApplicationRouting.config.HTTPApplicationRoutingZoneName
    #   id: aks_host
    # - uses: azure/k8s-bake@v1
    #   with:
    #     renderEngine: 'helm2'
    #     helmChart: '${{github.workspace}}/Deploy/helm/web' 
    #     helm-version: 'latest'
    #     overrides: |
    #       image.tag:gh-aad5aa4a3a1e79f288919ab2442d57946d980f17
    #       name:web
    #       image.repository:ivilches/tests
    #       ingress.hosts:fcacb0f417a84590bb54.eastus.aksapp.io
    #   id: bake 
    - name: Install Helm Chart
      shell: pwsh
      run: |
        helm repo update
        # helm upgrade --install web -f Deploy/helm/gvalues.yaml -f Deploy/helm/values.b2c.yaml --set inf.appinsights.id="" --set az.productvisitsurl="" --set ingress.hosts={$aksHost} --set image.repository=ivilches/tailwindtraders --set image.tag=${{ github.sha }}
        # helm upgrade --install -f Deploy/powershell/_values-gh.yaml --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/web --set image.tag=gh-${{ github.sha }} --set image.uploaderRepository=${{ secrets.ACR_NAME }}.azurecr.io/modeluploader --set image.uploaderTag=gh-${{ github.sha }} --set uploaderEnabled=false --set scaleWeb=true --set replicaCount=2 web  ${{ secrets.ACR_NAME }}/web --version=1.0.0-${{ github.sha }}
        Deploy\DeployWebAKS.ps1 -name web -aksName ${{ secrets.CLUSTER_NAME }} -resourceGroup ${{ secrets.RESOURCE_GROUP }} -tag gh-aad5aa4a3a1e79f288919ab2442d57946d980f17
