# Web Workflow

name: Web in AKS

on: [push]

jobs:
  buildpush:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    # - name: Docker build and push
    #   working-directory: Source/Tailwind.Traders.Web
    #   run: | 
    #     # docker build . --build-arg sdkTag=2.1 --build-arg runtimeTag=2.1 -t tailwindtraders/web:gh-${{ github.sha }} -t latest
    #     # docker push tailwindtraders/web:gh-${{ github.sha }}
    #     docker build . --build-arg sdkTag=2.1 --build-arg runtimeTag=2.1 -t ivilches/tailwindtraders:gh-${{ github.sha }} -t latest
    #     docker push ivilches/tailwindtraders:gh-${{ github.sha }}

    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Set AKS kubectl context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}
    # - name: Fetch AKS host
    #   shell: pwsh
    #   run: $(az aks show -n ${{ secrets.CLUSTER_NAME }} -g ${{ secrets.RESOURCE_GROUP }} | ConvertFrom-Json).addonProfiles.httpApplicationRouting.config.HTTPApplicationRoutingZoneName
    #   id: aks_host
    # - uses: azure/k8s-bake@v1
    #   with:
    #     renderEngine: 'helm2'
    #     helmChart: '${{github.workspace}}/Deploy/helm/web' 
    #     helm-version: 'latest'
    #     overrides: |
    #       image.tag:gh-aad5aa4a3a1e79f288919ab2442d57946d980f17
    #       name:web
    #       image.repository:ivilches/tests
    #       ingress.hosts:fcacb0f417a84590bb54.eastus.aksapp.io
    #   id: bake 

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh
        export PATH=/usr/local/bin/helm

    - name: Update repo helm
      shell: pwsh
      run: |
        helm repo add stable https://kubernetes-charts.storage.googleapis.com/
        helm repo update

    - name: Install Helm Chart
      # working-directory: ./Deploy
      shell: pwsh
      run: |
        helm upgrade --install web ./Deploy/helm/web -f ./Deploy/helm/gvalues.yaml -f ./Deploy/helm/values.b2c.yaml --set inf.appinsights.id="" --set ingress.hosts[0]=fcacb0f417a84590bb54.eastus.aksapp.io --set image.repository=ivilches/tailwindtraders --set image.tag=gh-2ab7f7516b35fff9f766ad0b2635b69e8474acbd --dry-run
