# Web Workflow

name: Web in AKS

on: [push]

jobs:
  buildpush:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1

    # - uses: azure/docker-login@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }} 
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    # - name: Docker build and push
    #   working-directory: Source/Tailwind.Traders.Web
    #   run: | 
    #     # docker build . --build-arg sdkTag=2.1 --build-arg runtimeTag=2.1 -t tailwindtraders/web:gh-${{ github.sha }} -t latest
    #     # docker push tailwindtraders/web:gh-${{ github.sha }}
    #     docker build . --build-arg sdkTag=2.1 --build-arg runtimeTag=2.1 -t ivilches/tailwindtraders:gh-${{ github.sha }} -t latest
    #     docker push ivilches/tailwindtraders:gh-${{ github.sha }}

    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    
    - name: Install aks-preview
      shell: pwsh
      run: |
        az extension add --name aks-preview

    - name: Get AKS host
      id: aks_host
      shell: pwsh
      run: echo "::set-output name=host_name::($(az aks show -n ${{ secrets.CLUSTER_NAME }} -g ${{ secrets.CLUSTER_RESOURCE_GROUP }} | ConvertFrom-Json).addonProfiles.httpApplicationRouting.config.HTTPApplicationRoutingZoneName)"
    
    - name: Set AKS kubectl context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh
        export PATH=/usr/local/bin/helm

    - name: Install Helm Chart
      shell: pwsh
      run: |
        # helm upgrade --install tailwindtraders-web ./Deploy/helm/web -f ./Deploy/helm/gvalues.yaml -f ./Deploy/helm/values.b2c.yaml --set ingress.protocol=http --set ingress.hosts[0]=fcacb0f417a84590bb54.eastus.aksapp.io --set image.repository=ivilches/tailwindtraders --set image.tag=gh-${{ github.sha }}
        helm upgrade --install tailwindtraders-web ./Deploy/helm/web -f ./Deploy/helm/gvalues.yaml -f ./Deploy/helm/values.b2c.yaml --set ingress.protocol=http --set ingress.hosts[0]=${{ steps.aks_host.outputs.host_name }} --set image.repository=ivilches/tailwindtraders --set image.tag=gh-d2e6b1d6ff6936db47877f461faf03533dd833c5