on: [push]

name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker build and push
      working-directory: Source/Tailwind.Traders.Web
      run: | 
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/tailwindtradersweb:gh-${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tailwindtradersweb:gh-${{ github.sha }} 

    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ secrets.CONTAINER_APPSERVICE_NAME }}
        app-settings-json: '${{ secrets.CONTAINER_APP_SETTINGS }}'

    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: ${{ secrets.CONTAINER_APPSERVICE_NAME }}
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/tailwindtradersweb:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout

        